In [151]:
# 모듈 로딩 및 
import numpy as np

In [152]:
# ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 ==> zeros()
np.zeros(2)

array([0., 0.])

In [153]:
np.zeros((2,3), dtype = np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [154]:
# 1로 채워진 ndarray 객체 생성 => ones()
np.ones(10), np.ones(10, dtype = np.int32)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [155]:
# 랜덤 데이터로 ndarray 객체 생성 ==> random
np.random.randint(1, 5, (3, 10))

# 1,2,3,4 중에서 랜덤으로 선택해서 3행 10열 생성함

array([[2, 2, 4, 1, 1, 4, 3, 3, 3, 4],
       [3, 3, 4, 4, 1, 3, 3, 4, 2, 3],
       [4, 2, 3, 4, 2, 4, 1, 2, 3, 4]])

In [156]:
# 0 <= 범위 < 1
np.random.rand(5, 2)

array([[0.25290961, 0.0474055 ],
       [0.92940665, 0.23614132],
       [0.81090494, 0.12618166],
       [0.07570637, 0.68558821],
       [0.94707403, 0.31567349]])

In [157]:
np.random.randn(5), np.random.randn(6,2,3)

(array([ 0.35099715,  0.3749871 ,  0.71201646,  0.73582661, -0.26122281]),
 array([[[ 1.04261732, -0.371615  ,  0.906895  ],
         [ 1.06395375, -0.58313364,  0.23533815]],
 
        [[ 0.62590409, -0.57606516,  0.56858375],
         [ 0.11599273, -0.15944566, -0.04440599]],
 
        [[-1.9344677 ,  0.2072362 ,  0.09739415],
         [-0.10913821,  0.6752176 ,  1.02096908]],
 
        [[ 0.52845098,  0.18180266, -0.11186876],
         [-1.59203303,  0.72865586, -0.33880365]],
 
        [[-2.14863262,  0.75642354,  0.00444073],
         [ 0.73305899, -0.08000291,  1.67389066]],
 
        [[-0.01070587, -0.140984  , -0.44136521],
         [-0.81838988,  0.81529132,  0.80843557]]]))

In [158]:
# 랜덤 고정
np.random.seed(4)

np.random.randn(5)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [159]:
data = np.random.randn(10)
print(data)
np.random.shuffle(data)
print(data)

[-1.58457724 -0.64770677  0.59857517  0.33225003 -1.14747663  0.61866969
 -0.08798693  0.4250724   0.33225315 -1.15681626]
[-1.14747663  0.33225315 -1.58457724  0.61866969 -0.08798693 -0.64770677
 -1.15681626  0.4250724   0.33225003  0.59857517]


In [160]:
data.sum(), data.max(), data.min()

(-2.317743386975293, 0.6186696890268814, -1.5845772351121241)

In [161]:
data.argmax(), data.argmin(), data.argsort()

(3, 2, array([2, 6, 0, 5, 4, 8, 1, 7, 9, 3], dtype=int64))

##### 넘파이 자습하긔

In [164]:
np.full((6,2,3), 8, dtype = float)

array([[[8., 8., 8.],
        [8., 8., 8.]],

       [[8., 8., 8.],
        [8., 8., 8.]],

       [[8., 8., 8.],
        [8., 8., 8.]],

       [[8., 8., 8.],
        [8., 8., 8.]],

       [[8., 8., 8.],
        [8., 8., 8.]],

       [[8., 8., 8.],
        [8., 8., 8.]]])

In [165]:
np.eye(1)

array([[1.]])

In [166]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [169]:
np.eye(10,k=2)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [173]:
np.empty((2,))

array([1.06599590e-311, 1.06599552e-311])

In [175]:
k = np.array([[1], [2], [3]])
np.ones_like(k)

array([[1],
       [1],
       [1]])

In [162]:
n