In [1]:
import cv2
import numpy as np

In [2]:
file = '../data/img/img_05_bms.jpg'
file_img = cv2.imread(file, cv2.IMREAD_GRAYSCALE)
file_img.shape, file_img.ndim

((500, 500), 2)

In [3]:
file_img

array([[100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       ...,
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100]], dtype=uint8)

In [4]:
# 까만 도화지 만들기
img = np.zeros((300, 300), dtype = np.uint8)
img.shape, img.ndim

((300, 300), 2)

In [5]:
# 흰 도화지 만들기
img2 = np.full((1000, 1000),255, dtype = np.uint8)
img2.shape, img2.ndim

((1000, 1000), 2)

In [6]:
# 이미지 데이터에 그림 그리기
cv2.line(img2, (10, 10), (700, 700), (0, 255, 255), 10)
print(img2)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [7]:
cv2.line(file_img, (10, 10), (400, 10), (255, 255, 0), 50)

array([[255, 255, 255, ..., 100, 100, 100],
       [255, 255, 255, ..., 100, 100, 100],
       [255, 255, 255, ..., 100, 100, 100],
       ...,
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100]], dtype=uint8)

In [14]:
cv2.imshow('img', img)
cv2.waitKey(delay= 100)
cv2.destroyAllWindows()

In [15]:
cv2.imshow('img2', img2)
cv2.waitKey(delay= 100)
cv2.destroyAllWindows()

In [16]:
cv2.imshow('file_img', file_img)
cv2.waitKey(delay= 100)
cv2.destroyAllWindows()

In [17]:
# 도화지 만들기

h, w = 500, 500
img_w = np.full((h, w),100, dtype = np.uint8)
ret = cv2.imwrite(file, img_w)

cv2.imshow('ret', ret)
cv2.waitKey(delay = 10)
cv2.destroyAllWindows()

In [18]:
# 글씨 그리기
file = '../data/img/img_03_twice.jpg'
file_img = cv2.imread(file)
file_img.shape, file_img.ndim

((500, 500, 3), 3)

In [13]:
# cv2.putText(file_img, 'plain', (50, 100), cv2.FONT_HERSHEY_PLAIN, 5, (51, 255,0))
# cv2.putText(file_img, 'Simplex', (100,100), cv2.FONT_HERSHEY_SIMPLEX, 5, (255,0,204))
# cv2.putText(file_img, 'Duplex', (150, 100), cv2.FONT_HERSHEY_DUPLEX, 5, (204, 255, 255))
# cv2.putText(file_img, 'Complex Small', (50, 300), cv2.FONT_HERSHEY_COMPLEX_SMALL, 5, (250, 0, 0))
cv2.putText(file_img, 'Script Complex', (50, 300), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 1, (250,0,0))

cv2.imshow('text+image', file_img)
cv2.waitKey(delay = 50000)
cv2.destroyAllWindows()